gymManageSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
	path('',views.home,name='home'),
	path('pagedetail/<int:id>',views.page_detail,name='pagedetail'),
	path('faq',views.faq_list,name='faq'),
	path('enquiry',views.enquiry,name='enquiry'),
	path('contact',views.contact_page,name='contact_page'),
	path('gallery',views.gallery,name='gallery'),
	path('gallerydetail/<int:id>',views.gallery_detail,name='gallery_detail'),
	path('pricing',views.pricing,name='pricing'),
	path('accounts/signup',views.signup,name='signup'),
	path('checkout/<int:plan_id>',views.checkout,name='checkout'),
	path('checkout_session/<int:plan_id>',views.checkout_session,name='checkout_session'),
	path('pay_success',views.pay_success,name='pay_success'),
	path('pay_cancel',views.pay_cancel,name='pay_cancel'),
	# User Dashboard Section Start
	path('user-dashboard',views.user_dashboard,name='user_dashboard'),
	path('update-profile',views.update_profile,name='update_profile'),
	# Trainer Login
	path('trainerlogin',views.trainerlogin,name='trainerlogin'),
	path('trainerlogout',views.trainerlogout,name='trainerlogout'),
	path('trainer_dashboard',views.trainer_dashboard,name='trainer_dashboard'),
	path('trainer_profile',views.trainer_profile,name='trainer_profile'),
	path('trainer_subscribers',views.trainer_subscribers,name='trainer_subscribers'),
	path('trainer_payments',views.trainer_payments,name='trainer_payments'),
	path('trainer_changepassword',views.trainer_changepassword,name='trainer_changepassword'),
	path('trainer_notifs',views.trainer_notifs,name='trainer_notifs'),
	# Notifications
	path('notifs',views.notifs,name='notifs'),
	path('get_notifs',views.get_notifs,name='get_notifs'),
	path('mark_read_notif',views.mark_read_notif,name='mark_read_notif'),
	# Messages
	path('messages',views.trainer_msgs,name='messages'),
	path('mark_read_trainer_notif',views.mark_read_trainer_notif,name='mark_read_trainer_notif'),
	path('report_for_user',views.report_for_user,name='report_for_user'),
	path('report_for_trainer',views.report_for_trainer,name='report_for_trainer'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

import json

# Banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Create your models here.
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Pages
class Page(models.Model):
	title=models.CharField(max_length=200)
	detail=models.TextField()

	def __str__(self):
		return self.title

# FAQ
class Faq(models.Model):
	quest=models.TextField()
	ans=models.TextField()

	def __str__(self):
		return self.quest

# Enquiry Model
class Enquiry(models.Model):
	full_name=models.CharField(max_length=150)
	email=models.CharField(max_length=150)
	detail=models.TextField()
	send_time=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.full_name

# Gallery Model
class Gallery(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="gallery/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Gallery Images
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))


# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validity_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	# subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title

# Package Discounts
class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# Subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

@receiver(post_save,sender=User)
def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(user=instance)

# Subscription
class Subscription(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	price=models.CharField(max_length=50)
	reg_date=models.DateField(auto_now_add=True,null=True)

# Trainer
class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/")
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# Notifications Json Response Via Ajax
class Notify(models.Model):
	notify_detail=models.TextField()
	read_by_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return str(self.notify_detail)

# Markas Read Notification By User
class NotifUserStatus(models.Model):
	notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Notification Status'

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)

# Trainer Notifications
class TrainerNotification(models.Model):
	notif_msg=models.TextField()

	def __str__(self):
		return str(self.notif_msg)

	def save(self,*args,**kwargs):
		super(TrainerNotification, self).save(*args,**kwargs)
		channel_layer=get_channel_layer()
		notif=self.notif_msg
		total=TrainerNotification.objects.all().count()
		async_to_sync(channel_layer.group_send)(
			'noti_group_name',{
				'type':'send_notification',
				'value':json.dumps({'notif':notif,'total':total})
			}
		)

# Markas Read Notification By Trainer
class NotifTrainerStatus(models.Model):
	notif=models.ForeignKey(TrainerNotification, on_delete=models.CASCADE)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Trainer Notification Status'

# SubscriberMsg
class TrainerMsg(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)
	message=models.TextField()

	class Meta:
		verbose_name_plural='Messages For Trainer'

# Reports
class TrainerSubscriberReport(models.Model):
	report_for_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_for_trainer')
	report_for_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_for_user')
	report_from_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_from_trainer',blank=True)
	report_from_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_from_user',blank=True)
	report_msg=models.TextField()

class AppSetting(models.Model):
	logo_img=models.ImageField(upload_to='app_logos/')

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.logo_img.url))

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
	class Meta:
		model=models.Enquiry
		fields=('full_name','email','detail')

class SignUp(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')

class TrainerLoginForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('username','pwd')

class TrainerProfileForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('full_name','mobile','address','detail','img')

class TrainerChangePassword(forms.Form):
	new_password=forms.CharField(max_length=50,required=True)

class ReportForTrainerForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_trainer','report_msg')

class ReportForUserForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_user','report_msg','report_from_trainer')
		widgets = {'report_from_trainer': forms.HiddenInput()}

class ReportForTrainerForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_trainer','report_msg','report_from_user')
		widgets = {'report_from_user': forms.HiddenInput()}

main/templates/user/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<div class="row">
				<div class="col-3">
					{% include 'user/left-sidebar.html' %}
				</div>
				<div class="col-9">
					<h3 class="mb-4 border-bottom pb-1">Dashboard</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="card">
								<h5 class="card-header">Current Package</h5>
								<ul class="list-group list-group-flush">
								    <li class="list-group-item">{{current_plan.plan}}</li>
								    <li class="list-group-item">Price: {{current_plan.price}}</li>
								    <li class="list-group-item">Validity: {{current_plan.plan.validity_days}} Days</li>
								    <li class="list-group-item">Purchase Date: {{current_plan.reg_date}}</li>
								    <li class="list-group-item">Expiry Date: {{enddate}}</li>
							  	</ul>
							</div>
						</div>
						<div class="col-md-6">
							<div class="card">
								<h5 class="card-header">Assigned Trainer</h5>
								<img src="{{my_trainer.trainer.img.url}}" class="card-img-top" alt="{{my_trainer.trainer}}">
								<div class="card-body">
									<h6 class="card-text">{{my_trainer.trainer}}</h6>
								</div>
								<div class="card-footer">
									<a href="{{my_trainer.trainer.facebook}}" title="Facebook"><i class="bi bi-facebook"></i></a>
									<a href="{{my_trainer.trainer.twitter}}" title="Twitter"><i class="bi bi-twitter"></i></a>
									<a href="{{my_trainer.trainer.youtube}}"><i class="bi bi-youtube" title="YouTube"></i></a>
									<a href="{{my_trainer.trainer.pinterest}}" title="Pinterest">P</a>
									<button data-bs-toggle="modal" data-bs-target="#AchivementModal" title="Achivement" class="float-end btn btn-sm btn-success"><i class="bi bi-trophy-fill"></i></button>

<!-- Modal -->
<div class="modal fade" id="AchivementModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{my_trainer.trainer.full_name}} Achivements</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
        	<thead>
        		<tr>
        			<th>Title</th>
        			<th>Image</th>
        			<th>Detail</th>
        		</tr>
        	</thead>
        	<tbody>
        		{% for achive in  my_trainer.trainer.trainerachivement_set.all %}
        		<tr>
	        		<td>{{achive.title}}</td>
	        		<td><img src="{{achive.img.url}}" width="80" /></td>
	        		<td>{{achive.detail}}</td>
	        	</tr>
	        	{% endfor %}
        	</tbody>
        </table>
      </div>
    </div>
  </div>
</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/user/left-sidebar.html
<div class="list-group">
	<a href="{% url 'user_dashboard' %}" class="list-group-item {% if request.path == '/user-dashboard' %} active {% endif %}">Dashboard</a>
	<a href="{% url 'update_profile' %}" class="list-group-item {% if request.path == '/update-profile' %} active {% endif %}">Profile</a>
	<a href="{% url 'password_change' %}" class="list-group-item {% if request.path == '/accounts/password_change/' %} active {% endif %}">Change Password</a>
	<a href="{% url 'notifs' %}" class="list-group-item {% if request.path == '/notifs' %} active {% endif %}">Notifications <span class="float-end badge bg-info mt-1">{{total_unread}}</span></a>
	<a href="#" class="list-group-item">Messages</a>
	<a href="{% url 'report_for_trainer' %}" class="list-group-item {% if request.path == '/report_for_trainer' %} active {% endif %}">Report for Trainer</a>
</div>

main/templates/user/update-profile.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<div class="row">
				<div class="col-3">
					{% include 'user/left-sidebar.html' %}
				</div>
				<div class="col-9">
					<h3 class="mb-4 border-bottom pb-1">Update Profile</h3>
					{% if msg %}
					<p class="text-success">{{msg}}</p>
					{% endif %}
					<form method="post" action="">
						<table class="table table-bordered">
							{% csrf_token %}
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}