gymManageSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
	path('',views.home,name='home'),
	path('pagedetail/<int:id>',views.page_detail,name='pagedetail'),
	path('faq',views.faq_list,name='faq'),
	path('enquiry',views.enquiry,name='enquiry'),
	path('contact',views.contact_page,name='contact_page'),
	path('gallery',views.gallery,name='gallery'),
	path('gallerydetail/<int:id>',views.gallery_detail,name='gallery_detail'),
	path('pricing',views.pricing,name='pricing'),
	path('accounts/signup',views.signup,name='signup'),
	path('checkout/<int:plan_id>',views.checkout,name='checkout'),
	path('checkout_session/<int:plan_id>',views.checkout_session,name='checkout_session'),
	path('pay_success',views.pay_success,name='pay_success'),
	path('pay_cancel',views.pay_cancel,name='pay_cancel'),
	# User Dashboard Section Start
	path('user-dashboard',views.user_dashboard,name='user_dashboard'),
	path('update-profile',views.update_profile,name='update_profile'),
	# Trainer Login
	path('trainerlogin',views.trainerlogin,name='trainerlogin'),
	path('trainerlogout',views.trainerlogout,name='trainerlogout'),
	path('trainer_dashboard',views.trainer_dashboard,name='trainer_dashboard'),
	path('trainer_profile',views.trainer_profile,name='trainer_profile'),
	path('trainer_subscribers',views.trainer_subscribers,name='trainer_subscribers'),
	path('trainer_payments',views.trainer_payments,name='trainer_payments'),
	path('trainer_changepassword',views.trainer_changepassword,name='trainer_changepassword'),
	path('trainer_notifs',views.trainer_notifs,name='trainer_notifs'),
	# Notifications
	path('notifs',views.notifs,name='notifs'),
	path('get_notifs',views.get_notifs,name='get_notifs'),
	path('mark_read_notif',views.mark_read_notif,name='mark_read_notif'),
	# Messages
	path('messages',views.trainer_msgs,name='messages'),
	path('mark_read_trainer_notif',views.mark_read_trainer_notif,name='mark_read_trainer_notif'),
	path('report_for_user',views.report_for_user,name='report_for_user'),
	path('report_for_trainer',views.report_for_trainer,name='report_for_trainer'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

import json

# Banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Create your models here.
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Pages
class Page(models.Model):
	title=models.CharField(max_length=200)
	detail=models.TextField()

	def __str__(self):
		return self.title

# FAQ
class Faq(models.Model):
	quest=models.TextField()
	ans=models.TextField()

	def __str__(self):
		return self.quest

# Enquiry Model
class Enquiry(models.Model):
	full_name=models.CharField(max_length=150)
	email=models.CharField(max_length=150)
	detail=models.TextField()
	send_time=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.full_name

# Gallery Model
class Gallery(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="gallery/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# Gallery Images
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))


# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validity_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	# subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title

# Package Discounts
class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# Subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

@receiver(post_save,sender=User)
def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(user=instance)

# Subscription
class Subscription(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	price=models.CharField(max_length=50)
	reg_date=models.DateField(auto_now_add=True,null=True)

# Trainer
class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/")
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# Notifications Json Response Via Ajax
class Notify(models.Model):
	notify_detail=models.TextField()
	read_by_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return str(self.notify_detail)

# Markas Read Notification By User
class NotifUserStatus(models.Model):
	notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Notification Status'

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)

# Trainer Notifications
class TrainerNotification(models.Model):
	notif_msg=models.TextField()

	def __str__(self):
		return str(self.notif_msg)

	def save(self,*args,**kwargs):
		super(TrainerNotification, self).save(*args,**kwargs)
		channel_layer=get_channel_layer()
		notif=self.notif_msg
		total=TrainerNotification.objects.all().count()
		async_to_sync(channel_layer.group_send)(
			'noti_group_name',{
				'type':'send_notification',
				'value':json.dumps({'notif':notif,'total':total})
			}
		)

# Markas Read Notification By Trainer
class NotifTrainerStatus(models.Model):
	notif=models.ForeignKey(TrainerNotification, on_delete=models.CASCADE)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Trainer Notification Status'

# SubscriberMsg
class TrainerMsg(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)
	message=models.TextField()

	class Meta:
		verbose_name_plural='Messages For Trainer'

# Reports
class TrainerSubscriberReport(models.Model):
	report_for_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_for_trainer')
	report_for_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_for_user')
	report_from_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_from_trainer',blank=True)
	report_from_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_from_user',blank=True)
	report_msg=models.TextField()

class AppSetting(models.Model):
	logo_img=models.ImageField(upload_to='app_logos/')

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.logo_img.url))

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
	class Meta:
		model=models.Enquiry
		fields=('full_name','email','detail')

class SignUp(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')

class TrainerLoginForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('username','pwd')

class TrainerProfileForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('full_name','mobile','address','detail','img')

class TrainerChangePassword(forms.Form):
	new_password=forms.CharField(max_length=50,required=True)

class ReportForTrainerForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_trainer','report_msg')

class ReportForUserForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_user','report_msg','report_from_trainer')
		widgets = {'report_from_trainer': forms.HiddenInput()}

class ReportForTrainerForm(forms.ModelForm):
	class Meta:
		model=models.TrainerSubscriberReport
		fields=('report_for_trainer','report_msg','report_from_user')
		widgets = {'report_from_user': forms.HiddenInput()}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <!-- Include jquery -->
    <script type="text/javascript" src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <title>Home - Arnold GYM</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
	  <div class="container">
	    <a class="navbar-brand" href="{% url 'home' %}">{{logo}}</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link btn btn-dark btn-sm text-white" href="{% url 'enquiry' %}">Enquiry</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            My Account
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
	          	{% if not request.user.is_authenticated %}
		            {% if request.session.trainerLogin %}
		            <li><a class="dropdown-item" href="{% url 'trainer_dashboard' %}">Dashboard</a></li>
		            <li><a class="dropdown-item" href="{% url 'trainerlogout' %}">Logout</a></li>
		            {% else %}
		            <li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a></li>
		            <li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
		            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
		            {% endif %}
	            {% else %}
	            <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a></li>
	            <li><a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a></li>
	            <li><a class="dropdown-item" href="#">Settings</a></li>
	            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
	            {% endif %}
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->

    {% block content %}

    {% endblock %}

   <!-- Footer Start -->
  <footer class="container py-5">
  <p class="float-end"><a href="#">Back to top</a></p>
  <p>© 2017–2021 Arnold GYM, Inc. · 
        <a href="{% url 'pagedetail' 2 %}">Privacy</a> · 
        <a href="{% url 'pagedetail' 3 %}">Terms</a> . 
        <a href="{% url 'faq' %}">FAQ</a> .
        <a href="{% url 'contact_page' %}">Contact Us</a> .
    </p>
</footer>

<!-- Bootstrap Bundle -->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript" src="{% static 'popper.min.js' %}"></script>
</body>
</html>

main/templates/cancel.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3>Sorry!! Please try again</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/contact_us.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Contact Us</h1>
			<div class="row">
				<div class="col-md-6">
					<table class="table table-bordered">
						<tr>
							<th>Address</th>
							<td>St-2, NYK</td>
						</tr>
						<tr>
							<th>Mobile</th>
							<td>+1 123456799</td>
						</tr>
						<tr>
							<th>Telephone</th>
							<td>123 7894562</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>arnoldgym@example.com</td>
						</tr>
					</table>
				</div>
				<div class="col-md-6">
					<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13690.667043024157!2d75.7865279!3d30.9239375!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x2b135ce266199a27!2sCode%20Artisan%20Lab!5e0!3m2!1sen!2sin!4v1632159340383!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/enquiry.jpg' %}" class="img-fluid" /> 
				</div>
				<div class="col-md-6">
					{% if msg %}
					<p class="text-success">{{msg}}</p>
					{% endif %}
					<form method="post" action="{% url 'enquiry' %}">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/faq.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
				{% for faq in faqs %}
				  <div class="accordion-item">
				    <h2 class="accordion-header" id="headingOne">
				      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
				        {{faq.quest}}
				      </button>
				    </h2>
				    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				      <div class="accordion-body">
				        {{faq.ans}}
				      </div>
				    </div>
				  </div>
				  {% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/gallery.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
			<div class="row">
				{% for gallery in gallerys %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title}}">
					  <div class="card-body">
					    <h5 class="card-title">{{gallery.title}}</h5>
					    <p class="card-text">{{gallery.detail}}</p>
					    <a href="{% url 'gallery_detail' gallery.id %}" class="btn btn-primary">View All</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/gallery_imgs.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Images</h1>
			<div class="row">
				{% for gimg in gallery_imgs %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gimg.img.url}}" class="card-img-top" alt="{{gimg.alt_text}}">
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/notifs.html
{% extends 'base.html' %}
{% block content %}
<style type="text/css">
	.marked{
		display: none;
	}
</style>
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<div class="row">
				<div class="col-3">
					{% include 'user/left-sidebar.html' %}
				</div>
				<div class="col-9">
					<h3 class="mb-4 border-bottom pb-1">Notifications <span class="badge bg-primary totalunread">123</span></h3>
					<span class="ajaxRes"></span>
					<ul class="list-group notif-list">
						
					</ul>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->

<script type="text/javascript">
	$(document).ready(function(){
		$(".ajaxRes").hide();
		setInterval(function(){
			$.ajax({
				url:"{% url 'get_notifs' %}",
				dataType:'json',
				beforeSend:function(){
					$(".ajaxRes").show();
					$(".ajaxRes").text('Loading...');
				},
				success:function(res){
					_html='';
					$(".totalunread").text(res.totalUnread);
					$.each(res.data,function(index,d){
						if(d.notifStatus==true){
							_html+='<li class="list-group-item list'+d.pk+'">'+d.notify_detail+'<button data-index="'+d.pk+'" data-notif="'+d.pk+'" class="btn btn-sm btn-secondary float-end markreadbtn markreadbtn'+d.pk+'"" style="display:none;">MarkRead</button><button class="float-end btn btn-success btn-sm marked'+d.pk+'"><i class="bi bi-check-square"></i></button></li>';
						}else{
							_html+='<li class="list-group-item bg-light list'+d.pk+'">'+d.notify_detail+'<button data-index="'+d.pk+'" data-notif="'+d.pk+'" class="btn btn-sm btn-secondary float-end markreadbtn markreadbtn'+d.pk+'"">MarkRead</button><button class="float-end btn btn-success btn-sm marked marked'+d.pk+'"><i class="bi bi-check-square"></i></button></li>';
						}
					});
					$(".notif-list").html(_html);
					$(".ajaxRes").hide();
				}
			});
		},5000);

		// MarkRead Section Start
		$(document).on("click",".markreadbtn",function(){
			var _index=$(this).attr('data-index');
			var _notif=$(this).attr('data-notif');

			$.ajax({
				url:"{% url 'mark_read_notif' %}",
				data:{
					notif:_notif
				},
				dataType:'json',
				beforeSend:function(){
					
				},
				success:function(res){
					if(res.bool==true){
						$(".list"+_index).removeClass('bg-light');
						$(".markreadbtn"+_index).hide();
						$(".marked"+_index).show();
					}
				}
			});
		});
		// End

	});
</script>

{% endblock %}

main/templates/orderemail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Order Email</title>
</head>
<body>
	<h3>{{title}}</h3>
</body>
</html>

main/templates/page.html
{% extends 'base.html' %}
{% block content %}
<!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{page.title}}</h1>
			<p>{{page.detail}}</p>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% load check_package %}
{% load mathfilters %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
<section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
<main>
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
        <div class="card-header py-3 text-white bg-primary border-primary">
          {% else %}
        <div class="card-header py-3">
          {% endif %}
          <h4 class="my-0 fw-normal">{{plan.title}}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">${{plan.price}}
            <small class="text-muted fw-light">/{{plan.validity_days}} Days</small>
          </h1>
          <p class="text-success">Member Capacity {{plan.max_member|sub:plan.total_members}}</p>
          <ul class="list-unstyled mt-3 mb-4">
            {% for feature in plan.subplanfeature_set.all %}
            <li>{{feature.title}}</li>
            {% endfor %}
          </ul>

          

          {% if request.user.is_authenticated %}
          {% check_user_package request.user.id plan.id as check_pckg %}
          {% check_pckg_validity request.user.id plan.id as check_validity %}

          {% if check_pckg %}
            {% if check_validity %}
              <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
            {% else %}
              <a href="#" class="w-100 btn btn-lg btn-dark disabled">Purchased</a>
            {% endif %}
          {% else %}
          <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}
          
          {% else %}
          <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <h2 class="display-6 text-center mb-4">Compare plans</h2>
  <div class="table-responsive">
    <table class="table text-center">
      <thead>
        <tr>
          <th style="width: 34%;"></th>
          {% for plan in plans %}
          <th style="width: 22%;">{{plan.title}}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for feature in dfeatures %}
        <tr>
          <th scope="row" class="text-start">{{feature.title}}</th>
          {% for plan in plans %}
          <td>
            {% if plan in feature.subplan.all %}
            <i class="bi bi-check-lg"></i>
            {% else %}
            <i class="bi bi-x-lg text-danger"></i>
            {% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
</section>
{% endblock %}